export interface ProductType {
  id: number, 
  name: string, 
  is_liked: boolean, 
  category_id: string, 
  description: string, 
  nasiya: string,
  summary: string,
  price: number,
  rating: number,
  brand_id: string,
  is_aksiya: boolean,
  image: string,
  createdAt: string,
  updatedAt: string,
  configurations: any[],
  product: any,
}